version: '3.8'

services:  
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecf-docker   
  
  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - ecf-docker   

  authentication-service:
    build:
      context: server/authentication-service
      dockerfile: Dockerfile
    ports:
      - "${AUTHENTICATION_SERVICE_PORT}:8080"
    environment:
      PORT: ${AUTHENTICATION_SERVICE_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_HOST: mysql-db
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}  
    depends_on:
      - mysql-db 
    networks:
      - ecf-docker  

  common-data-service:
    build:
      context: server/common-data-service
      dockerfile: Dockerfile
    ports:
      - "${COMMON_DATA_SERVICE_PORT}:8080"
    environment:
      PORT: ${COMMON_DATA_SERVICE_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_HOST: mysql-db
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - mysql-db
      - redis
    networks:
      - ecf-docker  

  payment-service:
    build:
      context: server/payment-service
      dockerfile: Dockerfile
    ports:
      - "${PAYMENT_SERVICE_PORT}"
    environment:
      PORT: ${PAYMENT_SERVICE_PORT} 
    networks:
      - ecf-docker  

  search-suggestion-service:
    build:
      context: server/search-suggestion-service
      dockerfile: Dockerfile
    ports:
      - "${SEARCH_SUGGESTION_SERVICE_PORT}:8080"
    environment:
      PORT: ${SEARCH_SUGGESTION_SERVICE_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}  
    depends_on:
      - common-data-service
    networks:
      - ecf-docker  

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${REACT_APP_PORT}:3000" 
    environment:
      REACT_APP_AUTHENTICATION_SERVICE_URL: ${REACT_APP_AUTHENTICATION_SERVICE_URL}
      REACT_APP_COMMON_DATA_SERVICE_URL: ${REACT_APP_COMMON_DATA_SERVICE_URL}
      REACT_APP_SEARCH_SUGGESTION_SERVICE_URL: ${REACT_APP_SEARCH_SUGGESTION_SERVICE_URL}
    depends_on:
      - authentication-service
      - common-data-service
      - payment-service
      - search-suggestion-service
    
networks:
  ecf-docker:

volumes:
  mysql-data:


